In [43]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
"""
1. Numerical Feature Scaling
    a) MinMax Scaler(0-1) ... (X -Xmin)/(Xmax - Xmin) MinMaxScaler.fit_transform()
    b) StandardScaler (X-Mean)/S.D ---> Z score       StandardScaler.fit_transform()
    c) Get back original Values  inverse_transform()
2. Categorical
    a) pd_dummy  Alternative to One hot encoding  pddummy = pd.get_dummies(cat,drop_first=True)
    b) OnHotEncoding ohe = OneHotEncoder()  arr = ohe.fit_transform(arr).toarray()
    c) LabelEncoding   le = LabelEncoder() arr = le.fit_transform(arr).reshape(-1,1)
    d) MeanEncoding     User Defined Funcyion Below
"""

In [29]:
df = pd.read_csv('test_file_for_feature_scaling.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   HouseNo  20 non-null     int64 
 1   Age      20 non-null     int64 
 2   Gender   20 non-null     object
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes


In [30]:
# Numerical Scaling
num_cols = df.select_dtypes(include=['int64'])
num_cols1 = num_cols
sc = MinMaxScaler()
sc1 = StandardScaler()
print(num_cols)

    HouseNo  Age
0       100    3
1       109   20
2       120   21
3       135   34
4       154   17
5       165   35
6       168   12
7       112    9
8       200    6
9       500   29
10      456   31
11      567   12
12      578   33
13      455   10
14      245   26
15      365   24
16      376   25
17      483   19
18      512    1
19      544    5


In [31]:
df1 = pd.DataFrame(sc.fit_transform(num_cols)) # MinMax
df2 = pd.DataFrame(sc1.fit_transform(num_cols1)) # Standard

In [42]:
df1.head()
sc.inverse_transform([[0,0]]) 

array([[100.,   1.]])

In [33]:
df2.head()

0         1
0 -1.233188 -1.467265
1 -1.182089  0.131678
2 -1.119635  0.225733
3 -1.034470  1.448454
4 -0.926595 -0.150489

In [35]:
# Categorical Feature Scaling
cat = df.select_dtypes(include = ['object'])

In [37]:
pddummy = pd.get_dummies(cat,drop_first=True) # drop_first is to remove dummy trap

In [67]:
# Label Encoding
arr = cat.values.reshape(-1) # shape must be (1D,) like (20,)
le = LabelEncoder()
arr = le.fit_transform(arr).reshape(-1,1)
arr

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [2],
       [1]])

In [68]:
# One hot Encoding Done after Label Encoding , alternative is pd.get_dummies
ohe = OneHotEncoder()
arr = ohe.fit_transform(arr).toarray()

In [69]:
arr

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [162]:
# Mean Encoding
me = mean_encoder(df,'Gender')

In [161]:
def mean_encoder(df,col_name):
    ix = list(np.array(df[col_name].value_counts().index))
    values = list(np.array(df[col_name].value_counts())) 
    total = sum(values)
    for i in range(0,len(values)):
        values[i] = values[i]/total
    arr = df[col_name].values
    for i in range(0,len(ix)):
        arr[arr==ix[i]] = values[i]
    return arr
    


array([0.55, 0.55, 0.35, 0.55, 0.55, 0.35, 0.1, 0.35, 0.35, 0.55, 0.55,
       0.55, 0.35, 0.55, 0.55, 0.35, 0.35, 0.55, 0.1, 0.55], dtype=object)

In [136]:
me1

0
0  (0.55, 0.35, 0.1)