In [1]:
# Multidim array
'''
use numpy
pip ---pip install package
'''
from numpy import *
# creating arrays
a1 = array([1,2,3,4,5])
a2 = arange(1,15,2) # stepwise like range functiokn
a3 = zeros(5) # returns float
a4 = ones(5) # returns float
a5 = linspace(1,40,11) # break 1n 11 parts from 1-40...by default part is 50
a6 = logspace(1,40,5) # break in 5 parts..10 raise to 1 to 10 raise to 40
print(f"a1 {a1}")
print(f"a2 {a2}")
print(f"a3 {a3}")
print(f"a4 {a4}")
print(f"a5 {a5}")
print(f"a6 {a6}")
print('%.2f' %a6[0])

# properties
print("Properties")
print(f"a1.size {a1.size}")
print(f"a1.dtype {a1.dtype}")
print(f"a1.ndim {a1.ndim}")
print(f"a1.shape {a1.shape}")

#Copy array
print("Copy array,info is commented out")
'''
1. just referencing  a1 = a2 ... same address
2. shallow copy  a2 = a1.view() ...different address but if one changed both changed
3. deep copy .... a2 = a1.copy() ... different address.. one changes another doesn't change
'''

#Matrix
a7 = arange(1,25,1)
print(a7.reshape(4,6),"Reshaped into 2D")
print(a7.reshape(3,4,2),"Reshaped into 3d")
print(a7.flatten(),"converted to 1D")
print(a7.reshape(3,4,2))
m = matrix(a7)
print(m, "Printing matrix")
m1  = matrix('1 2 5;3 4 8;5 6 9') # cols seprated by semicolon and cols by space
m2  = matrix('1 2 5;3 4 8;5 6 9')
print(m1+m2,"Adding of matrix")
print(m1*m2,"Multiplication")
print(diagonal(m1),"diagonal of matrix")
print(m1.max(),"Max of m1")
print(cos(m1))

a1 [1 2 3 4 5]
a2 [ 1  3  5  7  9 11 13]
a3 [0. 0. 0. 0. 0.]
a4 [1. 1. 1. 1. 1.]
a5 [ 1.   4.9  8.8 12.7 16.6 20.5 24.4 28.3 32.2 36.1 40. ]
a6 [1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
10.00
Properties
a1.size 5
a1.dtype int32
a1.ndim 1
a1.shape (5,)
Copy array,info is commented out
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] Reshaped into 2D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]] Reshaped into 3d
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] converted to 1D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]] Printing matrix
[[ 2  4 10]
 [ 6  8 16]
 [10 12 18]] Adding of matrix
[[ 32  40  66]
 [ 55  70 119]
 [ 68  88 154]] Multiplication
[1 4 9] dia