In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [6]:
"""
1. train_test_split  X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8)
2. Nulls and Not Nulls( For Imputing NAN values in columns)
"""

In [9]:
df = pd.read_csv('test_file_for_feature_scaling.csv')

In [18]:
X = np.array([10000,20000,30000,40000,50000,60000,70000,80000,90000,100000]).reshape(-1,1)
y = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8)

In [20]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[ 90000]
 [ 30000]
 [ 40000]
 [ 80000]
 [100000]
 [ 60000]
 [ 10000]
 [ 70000]]
[[50000]
 [20000]]
[[ 9]
 [ 3]
 [ 4]
 [ 8]
 [10]
 [ 6]
 [ 1]
 [ 7]]
[[5]
 [2]]


In [80]:
X = np.array([10000,np.nan,30000,40000,np.nan,60000,70000,80000,90000,100000])
y = np.array([1,2,3,4,5,6,7,8,9,10])

In [62]:
arr = np.array([X,y],ndmin=2)

In [66]:
arr = arr.T

In [74]:
df = pd.DataFrame(arr,columns=["Salary","Experience"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Salary      8 non-null      float64
 1   Experience  10 non-null     float64
dtypes: float64(2)
memory usage: 288.0 bytes


In [96]:
df_train = df.loc[df.Salary.isnull()]
df_test = df.loc[df.Salary.notnull()]

In [97]:
df2

Salary  Experience
0   10000.0         1.0
2   30000.0         3.0
3   40000.0         4.0
5   60000.0         6.0
6   70000.0         7.0
7   80000.0         8.0
8   90000.0         9.0
9  100000.0        10.0

In [98]:
df1

Salary  Experience
1     NaN         2.0
4     NaN         5.0