In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
arr3 = arr1 * arr2
print(arr3)

[ 1  4  9 16 25]


In [7]:
list_sqr = [i**2 for i in range(1,10)]
print(list_sqr)
arr1 = np.array(range(1,10))
print(arr1**2)

[1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 1  4  9 16 25 36 49 64 81]


In [10]:
arr1 = np.array([1,2,3,4])
arr2 = np.array((1,2,4,4))
print(arr1,"\n",arr2)

[1 2 3 4] 
 [1 2 4 4]


In [4]:
import numpy as np
list1 = [1,2,3]
list2 = [4,5,6] 
list3 = [7,8,9]
arr = np.array([list1,list2,list3])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
list_1 = [2,3,4,5] 
list_2 = [7,8,9,6] 
arr  = np.array(list_1) * np.array(list_2)
print(list(arr))
print(arr)
# list will contain commas but array won't contain that

[14, 24, 36, 30]
[14 24 36 30]


In [10]:
print(np.ones((5,3)))
print(np.ones((5,3)).dtype)
print(np.ones((5,3),dtype=int))
print(np.ones((2,)))  

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[1. 1.]


In [11]:
print(np.zeros((5,3)))
print(np.zeros((5,3)).dtype)
print(np.zeros((5,3),dtype=int))
print(np.zeros((2,)))  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[0. 0.]


In [12]:
print(np.random.random([3,4]))  # size of 3*4 and range will be in b/w 0 to 1

[[0.71008792 0.25503018 0.76999753 0.78301046]
 [0.41611541 0.74791829 0.61873488 0.26723674]
 [0.48496188 0.04777976 0.03443357 0.31298666]]


In [13]:
print(np.arange(10,100,5)) # 10 to 100 and increment of 5

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [24]:
np.linspace(10,100,5) # array of 1D 25 ..b/w 10 to 100

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [20]:
np.full((4,3),5)  # 1D array of size 4 and filling vale is 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
arr = np.ones(3,dtype=np.int)
print(np.tile(arr,3)) # create new array by multiplying 
print(np.tile(arr,(3,2)))

[1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [29]:
np.eye(3,dtype=np.int) # Identity Matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [31]:
np.random.randint(10,100,(3,4)) # matrix of 3*4 frm 10 to 100

array([[58, 27, 28, 77],
       [15, 66, 24, 29],
       [65, 65, 17, 37]])

In [35]:
a = np.random.random((5,8))

In [36]:
print(a.size)
print(a.ndim)
print(a.dtype)
print(a.itemsize) # memory used by each element

40
2
float64
8


In [38]:
a.reshape(5,2,4)

array([[[0.02682357, 0.93817779, 0.6151148 , 0.82405438],
        [0.7422121 , 0.9869795 , 0.23362459, 0.44688857]],

       [[0.53248486, 0.41030638, 0.62994122, 0.9228897 ],
        [0.84896307, 0.51376547, 0.3988775 , 0.98308472]],

       [[0.28171615, 0.61027889, 0.08214796, 0.7110975 ],
        [0.10719942, 0.29750211, 0.94194491, 0.90852334]],

       [[0.1339804 , 0.78089902, 0.61415506, 0.0923913 ],
        [0.83209228, 0.13904266, 0.90223756, 0.80482709]],

       [[0.72235673, 0.31623406, 0.80640112, 0.34961638],
        [0.17474037, 0.86591363, 0.60456917, 0.78729579]]])

In [39]:
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
# Third element
print(array_1d[2])  # 2

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])  # 2 5 6

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


In [41]:
array_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [44]:
print(array_2d[2,1])

12


In [45]:
print(array_2d[1,:])

[ 4  6  8 10]


In [46]:
print(array_2d[:,2])

[ 7  8 15]


In [48]:
print(array_2d[:,0:3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


In [62]:
n = int(input())
arr = np.ones((n,n),dtype=np.int)
arr[::2,::2] = 0
arr[1::2,1::2] = 0
arr

 2


array([[0, 1],
       [1, 0]])

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [63]:
arr = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])

In [64]:
arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [65]:
ncol = np.size(arr,1)
nrow = np.size(arr,0)
print(arr[:,0])
print(arr[0,:])
print(arr[:,ncol-1])
print(arr[nrow-1,:])

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [76]:
arr1 = np.array([[1,2],[5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([1,2,3,4,5])
print(arr1)
print(arr2)
arr4=np.hstack((arr1,arr2))
print(np.vstack((arr4,arr3)))

[[1 2]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 1 2 3]
 [5 6 4 5 6]
 [1 2 3 4 5]]


In [77]:
f = np.vectorize(lambda x:x+1)
print(arr4)
print(f(arr4))

[[1 2 1 2 3]
 [5 6 4 5 6]]
[[2 3 2 3 4]
 [6 7 5 6 7]]
